version: "3.9"

services:
  backend:
    build: ./library
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
   
  frontend: 
    build: ./task3-module-vi
    ports:
      - "5000:8080"
    
