version: "3.9"

services:
  backend:
    build: ./library
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
   
  frontend: 
    build: ./task3-module-vi
    ports:
      - "3000:8080"
    depends_on:
      - api

  api:
    image: node:14-alpine
    working_dir: /app
    volumes:
      - ./task3-module-vi/src/db:/app/src/db
    command: sh -c "npm install -g json-server && json-server --watch ./src/db/db.json --port 3000"    
